### ISSUE TITLE
Youtube urls

### ISSUE THREAD

**Issue by refriedfood** [ormanya/Supyiel#4]
For the life of my I cannot get this thing to grab youtube urls. Any help? (LastFM plugin)

**Comment by janalysis** [comment]
That functionality uses DDG to find the video links and DDG can be very cranky about what IPs it allows search requests from. Is it possible that is being blocked on the IP you are running your bot from @refriedfood ?

**Comment by ormanya** [comment]
It is likely an issue with the IP you are running the bot from and DDG limiting access. DDG gets cranky when it gets too many requests from an IP or IP range and has even completely blocked some ranges. No way around this except to use a different IP.
